analytics:
  twitter: null
  google: UA-75145409-1
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.65992
title: null
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.25
  brandStrength: 0.625
  rhythmicContrast: 0.75
  brandColors:
    - '#040404'
    - '#b9b9b9'
    - '#9a9a9a'
    - '#626262'
    - '#3c3c3c'
  lightness: 0.5625
purpose: []
favicon: null
name: H8V6.com
typography_spectrum: 1
