name: H8V6.com
favicon: null
layout_spectrum: 0.91243
typography_spectrum: 1
title: H8V6 Ltd.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75145409-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#b9b9b9'
    - '#9a9a9a'
    - '#626262'
    - '#3c3c3c'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
