name: xoxoxo
favicon: null
layout_spectrum: 0.46408
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181818'
    - '#979797'
    - '#6b6b6b'
    - '#484848'
    - '#c9c9c9'
  brandStrength: 0.0625
  lightness: 1
  saturation: 0.05668383650481701
  rhythmicContrast: 0.8106972111854702
purpose: []
