name: H8V6.com
favicon: null
layout_spectrum: 0.99266
typography_spectrum: 1
title: H8V6 Ltd.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75145409-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#b9b9b9'
    - '#9a9a9a'
    - '#626262'
    - '#3c3c3c'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
