name: H8V6.com
favicon: null
layout_spectrum: 0.19611
typography_spectrum: 1
title: H8V6 Ltd.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75145409-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050507'
    - '#fdfdfd'
    - '#743619'
    - '#e4b46e'
    - '#808988'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
