name: xoxoxo
favicon: null
layout_spectrum: 0.89443
typography_spectrum: 0.10795891052111983
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f8f3'
    - '#b0bdc3'
    - '#29343a'
    - '#8ea0ac'
    - '#618382'
  brandStrength: 0.8125
  lightness: 0.10897832503542304
  saturation: 0.05668383650481701
  rhythmicContrast: 0.8106972111854702
purpose: []
