name: H8V6.com
favicon: null
layout_spectrum: 0.19611
typography_spectrum: 1
title: H8V6 Ltd.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75145409-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#072c6d'
    - '#020202'
    - '#6c603d'
    - '#f6feff'
    - '#ce9f1d'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
