name: H8V6.com
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: H8V6 Ltd.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75145409-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181818'
    - '#979797'
    - '#6b6b6b'
    - '#484848'
    - '#c9c9c9'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
