name: xoxoxo
favicon: null
layout_spectrum: 0.89052
typography_spectrum: 1
title: H8V6 Ltd. Strategy consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75145409-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181818'
    - '#979797'
    - '#6b6b6b'
    - '#484848'
    - '#c9c9c9'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
